### ISSUE TITLE
Enhance resize events + once: true not working on iOS Safari

### ISSUE THREAD

**Issue by kilianso** [scroll-out/scroll-out#32]
`once: true` gets ignored by iOS Safari latest. Gets updated all the time an element scrolls into viewport.

It's because iOS Safari triggers a resize event once the browser bars disappear. So this line is the problem:
```
// Hook up document listeners to automatically detect changes.
win[ON](RESIZE, index);
```

If you change it to this it works as expected:
```
// Hook up document listeners to automatically detect changes.
win[ON](RESIZE, update);
```

Is there any reason why you are calling index() here instead of update()?
I think this is even more performant anyway.

**Comment by notoriousb1t** [comment]
I haven't heard any volunteering :smile:  so I will put it on my todos.

**Comment by kilianso** [comment]
Hey, sorry I haven't checked that issue few days. Would you still prefer a pull request?

**Comment by notoriousb1t** [comment]
Hah, don't worry about it. I tend to try to get people to do PRs for engagement (especially when they are straightforward).  Sometimes it takes me a week to get the time to write a patch due to life, and I try to give people opportunities instead of knocking out smaller things immediately.

I just pushed this under version 2.2.6.  Let me know if that works for you.
