### ISSUE TITLE
Not working for me

### ISSUE THREAD

**Issue by bsde1245** [scroll-out/scroll-out#40]
I am trying to add scroll effect to my [site](https://news.justinechacko.in/) here. What I did is add js file to head as `scroll.js`. I have `animate.css` in the head already.
I add `data-scroll` attribute to every element I want. Added following code in js file.
```
<script>
 ScrollOut({
  onShown: function(el) {
    // remove the class
    el.classList.remove("animated");

    // force reflow
    void el.offsetWidth;

    // re-add the animated cl
    el.classList.add("animated");
  }
});
</script>
```
animate on scroll not working, did I miss any step?

**EDIT**
I did like this,

```
var el = document.querySelector(".test");
el.setAttribute("data-scroll", "");
 ScrollOut({
   once: false,
  onShown: function(el) {
    // remove the class
    el.classList.remove("animated", "zoomIn");

    // force reflow
    void el.offsetWidth;

    // re-add the animated cl
    el.classList.add("animated", "zoomIn");
  }
});
```

Now first section gets animated on scroll. But remaining section targets not working.

**Comment by notoriousb1t** [comment]
I don't see the example site (does not load, probably because I missed this issue for so long :( ). 

Usually this kind of problem stems from the scrolling element not being the body/document element. The typical fix is to identify which element is actually scrolling and specify it in the ScrollOut constructor like so:

```js
ScrollOut({
  scrollingElement: '#theRealScrollingElement'
})
```

For reference, here is the appropriate documentation: https://scroll-out.github.io/guide.html#target-a-scroll-container.  Please let me know if that helps, and sorry for the late reply.

**Comment by bsde1234** [comment]
Link changed, Here is the [new one](https://blog.monsoonmalabar.com)

**Comment by notoriousb1t** [comment]
Try 

```js
 ScrollOut({
  targets: '.test',
  onShown: function(el) {
    // remove the class
    el.classList.remove("animated", "zoomIn");

    // force reflow
    void el.offsetWidth;

    // re-add the animated cl
    el.classList.add("animated", "zoomIn");
  }
});
```

**Comment by bsde1234** [comment]
I used this code [here](https://news.monsoonmalabar.com/). Small problem, in first load of website I get zoom effect two times. Any fix?
