### ISSUE TITLE
Why Scroll out not work with svg tag. Ex: g tag

### ISSUE THREAD

**Issue by ngocsangyem** [scroll-out/scroll-out#46]
Hi! I am working with svg and i have an issue. I try to add `data-scroll` to group tag (g) in svg to animate it. But Scroll out seems not work with svg

**Comment by notoriousb1t** [comment]
I haven't done much with detecting scroll on SVGs, but I suspect that it is because SVG and HTML are treated differently with respect to dimensions and position. Would you mind creating a CodePen example (or other sandbox)? I can see what can be done about improving compatibility.

What should work though is putting data-scroll on an html element surrounding the SVG itself and then using another selector to target the group:

```css
[data-scroll="in"] .svgGroup {}
```
